name: Build
on:
  push:
    branches: [master]
    tags: [v*]
permissions:
  contents: write
jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: |
            go.sum
            .goreleaser.yaml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: ${{ contains(github.ref, 'v') }}
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: ${{ ! contains(github.ref, 'v') }}
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: go-judge
          path: dist/*
